name: Smoke Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ðŸ§¬
        uses: actions/checkout@v3

      - name: Set up JDK 25 â˜•
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Run Smoke Tests ðŸš€
        run: mvn clean test -DincludeTags=smoke
        env:
          TOKEN_FOR_GIST: ${{secrets.TOKEN_FOR_GIST}}
